# Site settings
title: Global Blockchain Compliance Hub
email: milesgraham@neo.org
description: The repository for global blockchain compliance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://neo-project.github.io/global-blockchain-compliance-hub.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: none

theme: jekyll-theme-minimal
